(function() {var implementors = {};
implementors["collectives_polkadot_runtime"] = [{"text":"impl <a class=\"trait\" href=\"cumulus_pallet_dmp_queue/pallet/trait.Config.html\" title=\"trait cumulus_pallet_dmp_queue::pallet::Config\">Config</a> for <a class=\"struct\" href=\"collectives_polkadot_runtime/struct.Runtime.html\" title=\"struct collectives_polkadot_runtime::Runtime\">Runtime</a>","synthetic":false,"types":["collectives_polkadot_runtime::Runtime"]}];
implementors["contracts_rococo_runtime"] = [{"text":"impl <a class=\"trait\" href=\"cumulus_pallet_dmp_queue/pallet/trait.Config.html\" title=\"trait cumulus_pallet_dmp_queue::pallet::Config\">Config</a> for <a class=\"struct\" href=\"contracts_rococo_runtime/struct.Runtime.html\" title=\"struct contracts_rococo_runtime::Runtime\">Runtime</a>","synthetic":false,"types":["contracts_rococo_runtime::Runtime"]}];
implementors["parachain_template_runtime"] = [{"text":"impl <a class=\"trait\" href=\"cumulus_pallet_dmp_queue/pallet/trait.Config.html\" title=\"trait cumulus_pallet_dmp_queue::pallet::Config\">Config</a> for <a class=\"struct\" href=\"parachain_template_runtime/struct.Runtime.html\" title=\"struct parachain_template_runtime::Runtime\">Runtime</a>","synthetic":false,"types":["parachain_template_runtime::Runtime"]}];
implementors["penpal_runtime"] = [{"text":"impl <a class=\"trait\" href=\"cumulus_pallet_dmp_queue/pallet/trait.Config.html\" title=\"trait cumulus_pallet_dmp_queue::pallet::Config\">Config</a> for <a class=\"struct\" href=\"penpal_runtime/struct.Runtime.html\" title=\"struct penpal_runtime::Runtime\">Runtime</a>","synthetic":false,"types":["penpal_runtime::Runtime"]}];
implementors["rococo_parachain_runtime"] = [{"text":"impl <a class=\"trait\" href=\"cumulus_pallet_dmp_queue/pallet/trait.Config.html\" title=\"trait cumulus_pallet_dmp_queue::pallet::Config\">Config</a> for <a class=\"struct\" href=\"rococo_parachain_runtime/struct.Runtime.html\" title=\"struct rococo_parachain_runtime::Runtime\">Runtime</a>","synthetic":false,"types":["rococo_parachain_runtime::Runtime"]}];
implementors["statemine_runtime"] = [{"text":"impl <a class=\"trait\" href=\"cumulus_pallet_dmp_queue/pallet/trait.Config.html\" title=\"trait cumulus_pallet_dmp_queue::pallet::Config\">Config</a> for <a class=\"struct\" href=\"statemine_runtime/struct.Runtime.html\" title=\"struct statemine_runtime::Runtime\">Runtime</a>","synthetic":false,"types":["statemine_runtime::Runtime"]}];
implementors["statemint_runtime"] = [{"text":"impl <a class=\"trait\" href=\"cumulus_pallet_dmp_queue/pallet/trait.Config.html\" title=\"trait cumulus_pallet_dmp_queue::pallet::Config\">Config</a> for <a class=\"struct\" href=\"statemint_runtime/struct.Runtime.html\" title=\"struct statemint_runtime::Runtime\">Runtime</a>","synthetic":false,"types":["statemint_runtime::Runtime"]}];
implementors["westmint_runtime"] = [{"text":"impl <a class=\"trait\" href=\"cumulus_pallet_dmp_queue/pallet/trait.Config.html\" title=\"trait cumulus_pallet_dmp_queue::pallet::Config\">Config</a> for <a class=\"struct\" href=\"westmint_runtime/struct.Runtime.html\" title=\"struct westmint_runtime::Runtime\">Runtime</a>","synthetic":false,"types":["westmint_runtime::Runtime"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()