(function() {var implementors = {};
implementors["collectives_polkadot_runtime"] = [{"text":"impl Config for <a class=\"struct\" href=\"collectives_polkadot_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct collectives_polkadot_runtime::xcm_config::XcmConfig\">XcmConfig</a>","synthetic":false,"types":["collectives_polkadot_runtime::xcm_config::XcmConfig"]}];
implementors["parachain_template_runtime"] = [{"text":"impl Config for <a class=\"struct\" href=\"parachain_template_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct parachain_template_runtime::xcm_config::XcmConfig\">XcmConfig</a>","synthetic":false,"types":["parachain_template_runtime::xcm_config::XcmConfig"]}];
implementors["penpal_runtime"] = [{"text":"impl Config for <a class=\"struct\" href=\"penpal_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct penpal_runtime::xcm_config::XcmConfig\">XcmConfig</a>","synthetic":false,"types":["penpal_runtime::xcm_config::XcmConfig"]}];
implementors["rococo_parachain_runtime"] = [{"text":"impl Config for <a class=\"struct\" href=\"rococo_parachain_runtime/struct.XcmConfig.html\" title=\"struct rococo_parachain_runtime::XcmConfig\">XcmConfig</a>","synthetic":false,"types":["rococo_parachain_runtime::XcmConfig"]}];
implementors["shell_runtime"] = [{"text":"impl Config for <a class=\"struct\" href=\"shell_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct shell_runtime::xcm_config::XcmConfig\">XcmConfig</a>","synthetic":false,"types":["shell_runtime::xcm_config::XcmConfig"]}];
implementors["statemine_runtime"] = [{"text":"impl Config for <a class=\"struct\" href=\"statemine_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct statemine_runtime::xcm_config::XcmConfig\">XcmConfig</a>","synthetic":false,"types":["statemine_runtime::xcm_config::XcmConfig"]}];
implementors["statemint_runtime"] = [{"text":"impl Config for <a class=\"struct\" href=\"statemint_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct statemint_runtime::xcm_config::XcmConfig\">XcmConfig</a>","synthetic":false,"types":["statemint_runtime::xcm_config::XcmConfig"]}];
implementors["westmint_runtime"] = [{"text":"impl Config for <a class=\"struct\" href=\"westmint_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct westmint_runtime::xcm_config::XcmConfig\">XcmConfig</a>","synthetic":false,"types":["westmint_runtime::xcm_config::XcmConfig"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()